<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-05T10:46:47 CDT" name="Suite" finished-at="2021-11-05T10:46:57 CDT" duration-ms="9833">
    <groups>
      <group name="regression">
        <method signature="LoginNegativeTest.invalidPasswordTest()[pri:1, instance:loginTest.LoginNegativeTest@72bc6553]" name="invalidPasswordTest" class="loginTest.LoginNegativeTest"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="LoginNegativeTest.invalidLoginTest()[pri:0, instance:loginTest.LoginNegativeTest@72bc6553]" name="invalidLoginTest" class="loginTest.LoginNegativeTest"/>
        <method signature="LoginNegativeTest.invalidPasswordTest()[pri:1, instance:loginTest.LoginNegativeTest@72bc6553]" name="invalidPasswordTest" class="loginTest.LoginNegativeTest"/>
        <method signature="LoginNegativeTest.invalidUserNameTest()[pri:2, instance:loginTest.LoginNegativeTest@72bc6553]" name="invalidUserNameTest" class="loginTest.LoginNegativeTest"/>
        <method signature="LoginPositiveTest.positiveLoginTest()[pri:0, instance:loginTest.LoginPositiveTest@536f2a7e]" name="positiveLoginTest" class="loginTest.LoginPositiveTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2021-11-05T10:46:47 CDT" name="Test" finished-at="2021-11-05T10:46:57 CDT" duration-ms="9833">
      <class name="loginTest.LoginPositiveTest">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:loginTest.LoginPositiveTest@536f2a7e]" started-at="2021-11-05T10:46:47 CDT" name="openApplication" finished-at="2021-11-05T10:46:50 CDT" duration-ms="3058" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="positiveLoginTest()[pri:0, instance:loginTest.LoginPositiveTest@536f2a7e]" started-at="2021-11-05T10:46:50 CDT" name="positiveLoginTest" finished-at="2021-11-05T10:46:52 CDT" duration-ms="1489" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [A Product of Bost IT Solution - Inventory1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [A Product of Bost IT Solution - Inventory1]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at loginTest.LoginPositiveTest.positiveLoginTest(LoginPositiveTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveLoginTest -->
        <test-method is-config="true" signature="finishTest()[pri:0, instance:loginTest.LoginPositiveTest@536f2a7e]" started-at="2021-11-05T10:46:54 CDT" name="finishTest" finished-at="2021-11-05T10:46:54 CDT" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finishTest -->
      </class> <!-- loginTest.LoginPositiveTest -->
      <class name="loginTest.LoginNegativeTest">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:loginTest.LoginNegativeTest@72bc6553]" started-at="2021-11-05T10:46:54 CDT" name="openApplication" finished-at="2021-11-05T10:46:55 CDT" duration-ms="1371" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="invalidLoginTest()[pri:0, instance:loginTest.LoginNegativeTest@72bc6553]" started-at="2021-11-05T10:46:55 CDT" name="invalidLoginTest" finished-at="2021-11-05T10:46:55 CDT" duration-ms="203" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method signature="invalidPasswordTest()[pri:1, instance:loginTest.LoginNegativeTest@72bc6553]" started-at="2021-11-05T10:46:55 CDT" name="invalidPasswordTest" finished-at="2021-11-05T10:46:56 CDT" duration-ms="819" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidPasswordTest -->
        <test-method signature="invalidUserNameTest()[pri:2, instance:loginTest.LoginNegativeTest@72bc6553]" started-at="2021-11-05T10:46:56 CDT" name="invalidUserNameTest" finished-at="2021-11-05T10:46:57 CDT" duration-ms="800" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUserNameTest -->
        <test-method is-config="true" signature="finishTest()[pri:0, instance:loginTest.LoginNegativeTest@72bc6553]" started-at="2021-11-05T10:46:57 CDT" name="finishTest" finished-at="2021-11-05T10:46:57 CDT" duration-ms="134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finishTest -->
      </class> <!-- loginTest.LoginNegativeTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
